### ISSUE TITLE
Slow import with tensorflow_probability

### ISSUE THREAD

**Issue by patel-zeel** [wesselb/stheno#25]
### Description of the bug

Hi @wesselb, when I try to import stheno with tensorflow_probability (reproduced in a fresh Google colab environment), it takes a long time, around 30 seconds. 

| Code | Time taken |
| ------|--------------|
| <pre>from time import time<br>init = time()<br>import tensorflow_probability.substrates.jax as tfp<br>from stheno import GP, EQ, PseudoObs, PseudoObservationsFITC, PseudoObsDTC<br>print(time()-init)</pre>| 28 seconds |
| <pre>from time import time<br>init = time()<br>from stheno import GP, EQ, PseudoObs, PseudoObservationsFITC, PseudoObsDTC<br>print(time()-init)</pre>| 3.6 seconds |
| <pre>from time import time<br>init = time()<br>import tensorflow_probability.substrates.jax as tfp<br>print(time()-init)</pre>| 3.79 seconds |

**Comment by wesselb** [comment]
Hey @patel-zeel! Thanks for opening an issue.

I can confirm that the load times are indeed slow. My suspicion is that [Plum](https://github.com/wesselb/plum) is to blame here, which recently started using `inspect` to check whether or not `from __future__ import annotations` is loaded or not. This mechanism should be improved soon, at which point this performance issue should automatically disappear. Hence, for now, unless this is blocking you, I'll leave this open, and revise the issue once the mechanism is Plum has been improved.

**Comment by wesselb** [comment]
Hey @patel-zeel! With the new release of Plum, this issue should now be fixed.
